- name: install freeradius service
  apt: name=freeradius state=installed update_cache=yes

- name: apply radius client configuration
  copy: src=clients.conf dest=/etc/freeradius/clients.conf
  notify:
    - restart radius

- name: apply user configuration
  copy: src=users dest=/etc/freeradius/users
  notify:
    - restart radius
